/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CONTROLADOR.ClienteDAO;
import MODELO.Cliente;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author pablo
 */
public class AgregarClienteVehiculoUI extends javax.swing.JFrame {

    
       TableRowSorter trs;
    
    
    public AgregarClienteVehiculoUI() {
        initComponents();
        setLocationRelativeTo(null);
        listarCli();
        cerrar();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/logoServi2.png")).getImage());
    
     
     btnRegistrarClienVehi.setEnabled(false);
     btnEliminar.setEnabled(false);
     btnEditar.setEnabled(false);

    }
    
    
      public void cerrar()
    {
        try {
            
                this.setDefaultCloseOperation(AgregarClienteVehiculoUI.DO_NOTHING_ON_CLOSE);
                addWindowListener(new WindowAdapter() {
                    public void windowClosing(WindowEvent e){
                        confirmarSalida();
                    }
                });
                this.setVisible(true);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
      
     public void confirmarSalida()
    {
        int valor= JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea cerrar la apliación Serviexpress?","Advertencia", JOptionPane.YES_NO_OPTION);
        if(valor==JOptionPane.YES_OPTION)
        {
            JOptionPane.showMessageDialog(null,"Gracias, hasta pronto","Gracias",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }
      
      private void listarCli(){
        
        ClienteDAO dao = new ClienteDAO(); 
       tablaClientes.setModel(dao.listarClientes());
        
        
    }
      
    public void habilitarBotonGuardarCli()
    {
        
            if(!txtRutCliente.getText().isEmpty() && 
            !txtNombreCliente.getText().isEmpty() &&
              !txtApellidoClien.getText().isEmpty() &&
                !txtCorreoClien.getText().isEmpty() &&
                 !txtDireccionClie.getText().isEmpty() &&
                   !txtTelefonoClie.getText().isEmpty() &&
                      !txtUserNameClie.getText().isEmpty() &&
                        !txtPassClie.getText().isEmpty())
        {
           btnRegistrarClienVehi.setEnabled(true);
        }
        else{
            
            btnRegistrarClienVehi.setEnabled(false);
        }
        
    }
    
    public void habilitarbotonEditar()
    {
           if(!txtRutCliente.getText().isEmpty() && 
            !txtNombreCliente.getText().isEmpty() &&
              !txtApellidoClien.getText().isEmpty() &&
                !txtCorreoClien.getText().isEmpty() &&
                 !txtDireccionClie.getText().isEmpty() &&
                   !txtTelefonoClie.getText().isEmpty() &&
                      !txtUserNameClie.getText().isEmpty() &&
                        !txtPassClie.getText().isEmpty())
        {
           btnEditar.setEnabled(true);
        }
        else{
            
           btnEditar.setEnabled(false);
        }
    }
    
    public void habilitarbotonEliminar()
    {
          
           
           if(!txtRutCliente.getText().isEmpty() && 
            !txtNombreCliente.getText().isEmpty() &&
              !txtApellidoClien.getText().isEmpty() &&
                !txtCorreoClien.getText().isEmpty() &&
                 !txtDireccionClie.getText().isEmpty() &&
                   !txtTelefonoClie.getText().isEmpty() &&
                      !txtUserNameClie.getText().isEmpty() &&
                        !txtPassClie.getText().isEmpty())
        {
           btnEliminar.setEnabled(true);
        }
        else{
            
           btnEliminar.setEnabled(false);
        }
        
    }
    
      
    private void LimpiarCliente()
    {
            txtRutCliente.setText("");
            txtNombreCliente.setText("");
            txtApellidoClien.setText("");
            txtCorreoClien.setText("");
            txtDireccionClie.setText("");
            txtTelefonoClie.setText("");
            txtUserNameClie.setText("");
            txtPassClie.setText("");
            
            
            
    }
      
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        txtRutCliente = new javax.swing.JTextField();
        txtCorreoClien = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        txtApellidoClien = new javax.swing.JTextField();
        txtDireccionClie = new javax.swing.JTextField();
        txtTelefonoClie = new javax.swing.JTextField();
        txtUserNameClie = new javax.swing.JTextField();
        txtPassClie = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnRegistrarClienVehi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        btnLimpiar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtFiltrarporNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 690, 800, 0));

        txtRutCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtRutCliente.setToolTipText("Ingresar Rut Cliente");
        txtRutCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        txtRutCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutClienteActionPerformed(evt);
            }
        });
        txtRutCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRutClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRutClienteKeyTyped(evt);
            }
        });
        jPanel1.add(txtRutCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 141, -1));

        txtCorreoClien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCorreoClien.setToolTipText("Correo de Contacto");
        txtCorreoClien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        txtCorreoClien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorreoClienKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoClienKeyTyped(evt);
            }
        });
        jPanel1.add(txtCorreoClien, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 141, -1));

        txtNombreCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNombreCliente.setToolTipText("Nombre del Cliente");
        txtNombreCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        txtNombreCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreClienteKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 141, -1));

        txtApellidoClien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtApellidoClien.setToolTipText("Apellido del Cliente");
        txtApellidoClien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        txtApellidoClien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoClienKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoClienKeyTyped(evt);
            }
        });
        jPanel1.add(txtApellidoClien, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 141, -1));

        txtDireccionClie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDireccionClie.setToolTipText("Dirección del Cliente");
        txtDireccionClie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        txtDireccionClie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDireccionClieKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionClieKeyTyped(evt);
            }
        });
        jPanel1.add(txtDireccionClie, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 141, -1));

        txtTelefonoClie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTelefonoClie.setToolTipText("Telefono de contacto ");
        txtTelefonoClie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        txtTelefonoClie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoClieKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoClieKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefonoClie, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 141, -1));

        txtUserNameClie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtUserNameClie.setToolTipText("Nombre Usuario");
        txtUserNameClie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        txtUserNameClie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserNameClieKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserNameClieKeyTyped(evt);
            }
        });
        jPanel1.add(txtUserNameClie, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 141, -1));

        txtPassClie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPassClie.setToolTipText("Contraseña");
        txtPassClie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        txtPassClie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassClieKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassClieKeyTyped(evt);
            }
        });
        jPanel1.add(txtPassClie, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 142, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1870, 67, 800, 10));

        btnRegistrarClienVehi.setBackground(new java.awt.Color(102, 102, 255));
        btnRegistrarClienVehi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarClienVehi.setText("Registrar");
        btnRegistrarClienVehi.setToolTipText("Guarda los datos del cliente ");
        btnRegistrarClienVehi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        btnRegistrarClienVehi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienVehiActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarClienVehi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 160, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Rut cliente:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Dirección:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("nombre de usuario:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("contraseña:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("telefono:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("correo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Recepción Cliente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1870, 679, 822, 0));

        btnEditar.setBackground(new java.awt.Color(102, 102, 255));
        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditar.setText("Actualizar");
        btnEditar.setToolTipText("Actualiza los datos de un Cliente ya ingresado en el sistema");
        btnEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 110, 30));

        tablaClientes.setBackground(new java.awt.Color(102, 255, 102));
        tablaClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        tablaClientes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaClientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 500, 160));

        btnEliminar.setBackground(new java.awt.Color(102, 102, 255));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("Elimina A un Cliente de la base de datos");
        btnEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 110, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 72, 810, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 580, -1));

        btnLimpiar.setBackground(new java.awt.Color(102, 102, 255));
        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpiar.setText("Nuevo ");
        btnLimpiar.setToolTipText("Limpia los datos del formulario de Cliente");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 110, 30));

        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_exit_40px_1.png"))); // NOI18N
        jLabel10.setText("Salir");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(102, 102, 255));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar ");
        btnBuscar.setToolTipText("Busca por rut los datos del Cliente");
        btnBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, 110, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Recepción Cliente");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Filtrar por nombre:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, -1, 30));

        txtFiltrarporNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtFiltrarporNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        txtFiltrarporNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiltrarporNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtFiltrarporNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRutClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutClienteActionPerformed

    private void btnRegistrarClienVehiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienVehiActionPerformed
       
          int i = JOptionPane.showConfirmDialog(this, "¿Estas seguro que deseas Registrar este cliente?"); 
          if(i==0){
              
                
          if(txtRutCliente.getText().isEmpty() || 
            txtNombreCliente.getText().isEmpty() ||
              txtApellidoClien.getText().isEmpty() ||
                txtCorreoClien.getText().isEmpty() ||
                 txtDireccionClie.getText().isEmpty() ||
                   txtTelefonoClie.getText().isEmpty() ||
                      txtUserNameClie.getText().isEmpty() ||
                        txtPassClie.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }
        else{
            
            Cliente modelC = new Cliente();
            ClienteDAO daoC = new ClienteDAO(); 
 
              
              modelC.setRutClien(txtRutCliente.getText());
              modelC.setNombreClien(txtNombreCliente.getText());
              modelC.setApellClien(txtApellidoClien.getText());
              modelC.setCorreoClien(txtCorreoClien.getText());
              modelC.setDirecClien(txtDireccionClie.getText());
              modelC.setTelefonoClien(Integer.parseInt(txtTelefonoClie.getText()));
              modelC.setUserNameCli(txtUserNameClie.getText());
              modelC.setPassClien(txtPassClie.getText());
     
              if(daoC.registroCliente(modelC))
              {
               JOptionPane.showMessageDialog(null, "Se registro al Cliente con exito");
               listarCli();
               LimpiarCliente();
               habilitarBotonGuardarCli();
              } 
             
            }  
                                              
          } else if(i==1){
              
              
              JOptionPane.showMessageDialog(this, "Se cancelo el registro del cliente");
          }
        
      
    }//GEN-LAST:event_btnRegistrarClienVehiActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        int i = JOptionPane.showConfirmDialog(this, "¿Estas seguro que deseas eliminar el cliente?"); 
       
        if(i==0){
            
                    
        
        Cliente modelC = new Cliente(); 
        ClienteDAO Cdao = new ClienteDAO(); 
        modelC.setRutClien(txtRutCliente.getText());
        modelC.setNombreClien(txtNombreCliente.getText());
        modelC.setApellClien(txtApellidoClien.getText());
        modelC.setCorreoClien(txtCorreoClien.getText());
        modelC.setDirecClien(txtDireccionClie.getText());
        modelC.setTelefonoClien(Integer.parseInt(txtTelefonoClie.getText()));
        modelC.setUserNameCli(txtUserNameClie.getText());
        modelC.setPassClien(txtPassClie.getText());
        if(Cdao.eliminarCLiente(modelC))
        {
            JOptionPane.showMessageDialog(null, "Se Elimino al Cliente con exito");
            listarCli();
            LimpiarCliente();
            habilitarbotonEliminar();
        
        }
            
        } else if(i==1) {
            
            JOptionPane.showMessageDialog(this, "Se cancelo la eliminacion del cliente");
        }

      
      
        
        
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMouseClicked
        
        int seleccion = tablaClientes.rowAtPoint(evt.getPoint());
        
        txtRutCliente.setText(tablaClientes.getValueAt(seleccion, 0)+"");
        txtNombreCliente.setText(tablaClientes.getValueAt(seleccion, 1)+"");
        txtApellidoClien.setText(tablaClientes.getValueAt(seleccion, 2)+"");
        txtCorreoClien.setText(tablaClientes.getValueAt(seleccion, 3)+"");
        txtDireccionClie.setText(tablaClientes.getValueAt(seleccion, 4)+"");
        txtTelefonoClie.setText(tablaClientes.getValueAt(seleccion, 5)+"");
        txtUserNameClie.setText(tablaClientes.getValueAt(seleccion, 6)+"");
        txtPassClie.setText(tablaClientes.getValueAt(seleccion, 7)+"");
        
       // habilitarBotonGuardarCli();
        habilitarbotonEliminar();
        habilitarbotonEditar();
        
        
        
    }//GEN-LAST:event_tablaClientesMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        
          LimpiarCliente();
          habilitarBotonGuardarCli();
          habilitarbotonEliminar();
          habilitarbotonEditar();
            
            
            
            
        
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
     
            int i = JOptionPane.showConfirmDialog(this, "¿Estas seguro que deseas actualizar los datos del cliente?"); 
            if(i==0){
                
                    if(txtRutCliente.getText().isEmpty())
            {
                       String mensaje = "debe seleccionar un RUT para editar"; 
                      JOptionPane.showMessageDialog(null, mensaje);
            }
            else{
                
                   Cliente modelC = new Cliente();
                  ClienteDAO daoC = new ClienteDAO(); 
              
           
              
              modelC.setRutClien(txtRutCliente.getText());
              modelC.setNombreClien(txtNombreCliente.getText());
              modelC.setApellClien(txtApellidoClien.getText());
              modelC.setCorreoClien(txtCorreoClien.getText());
              modelC.setDirecClien(txtDireccionClie.getText());
              modelC.setTelefonoClien(Integer.parseInt(txtTelefonoClie.getText()));
              modelC.setUserNameCli(txtUserNameClie.getText());
              modelC.setPassClien(txtPassClie.getText());
              daoC.ModificarCliente(modelC); 
              
              String mensaje ="Cliente Modificado con exito"; 
              
              JOptionPane.showMessageDialog(null, mensaje);
              listarCli();
              habilitarbotonEditar();
              
                
            }
                
                
         }else if(i==1){
             
               JOptionPane.showMessageDialog(this, "Se cancelo la actualizacion de datos del cliente");
             
         }
        
        
           
             
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtRutClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutClienteKeyTyped
        
        int numerocaracteres = 10; 
        
        if(txtRutCliente.getText().length() >= numerocaracteres) {
            evt.consume();
   
            JOptionPane.showMessageDialog(rootPane, "El RUT no puede tener mas de 10 Caracteres");
        }
        
        
        
    }//GEN-LAST:event_txtRutClienteKeyTyped

    private void txtNombreClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreClienteKeyTyped
        
        char c = evt.getKeyChar(); 
        
        if(!Character.isLetter(c)){
            evt.consume();

        }
        
     
        
        
        
      int numerocaracteres = 30; 
        
        if(txtNombreCliente.getText().length() >= numerocaracteres) {
            evt.consume();
   
            JOptionPane.showMessageDialog(rootPane, "El Nombre no puede tener mas de 30 Caracteres");
        }
        
        
        
    }//GEN-LAST:event_txtNombreClienteKeyTyped

    private void txtApellidoClienKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoClienKeyTyped
       
        char c = evt.getKeyChar(); 
        
        if(!Character.isLetter(c)){
            evt.consume();
        }
        
        
        int numerocaracteres = 30; 
        
        if(txtApellidoClien.getText().length() >= numerocaracteres) {
            evt.consume();
   
            JOptionPane.showMessageDialog(rootPane, "El Apellido no puede tener mas de 30 Caracteres");
        }
        
        
        
        
    }//GEN-LAST:event_txtApellidoClienKeyTyped

    private void txtDireccionClieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionClieKeyTyped
        
        int numerocaracteres = 30; 
        
        if(txtDireccionClie.getText().length() >= numerocaracteres) {
            evt.consume();
   
            JOptionPane.showMessageDialog(rootPane, "La Dirección no puede tener mas de 30 Caracteres");
        }
        
        
    }//GEN-LAST:event_txtDireccionClieKeyTyped

    private void txtCorreoClienKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoClienKeyTyped
        
         int numerocaracteres = 30; 
        
        if(txtCorreoClien.getText().length() >= numerocaracteres) {
            evt.consume();
   
            JOptionPane.showMessageDialog(rootPane, "El Correo no puede tener mas de 30 Caracteres");
        }
        
        
    }//GEN-LAST:event_txtCorreoClienKeyTyped

    private void txtTelefonoClieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoClieKeyTyped
       
          char c = evt.getKeyChar(); 
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
        
        int numerocaracteres = 9; 
        
        if(txtTelefonoClie.getText().length() >= numerocaracteres) {
            evt.consume();
   
            JOptionPane.showMessageDialog(rootPane, "el numero de telefono no puede ser mas de 9 digitos");
        }
        
        
        
    }//GEN-LAST:event_txtTelefonoClieKeyTyped

    private void txtPassClieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassClieKeyTyped
        
        
        int numerocaracteres = 30; 
        
        if(txtPassClie.getText().length() >= numerocaracteres) {
            evt.consume();
   
            JOptionPane.showMessageDialog(rootPane, "La contraseña no puede tener mas de 30 Caracteres");
        }
        
        
    }//GEN-LAST:event_txtPassClieKeyTyped

    private void txtUserNameClieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameClieKeyTyped
     
          int numerocaracteres = 30; 
        
        if(txtUserNameClie.getText().length() >= numerocaracteres) {
            evt.consume();
   
            JOptionPane.showMessageDialog(rootPane, "El nombre de usuario demasiado largo");
        }
        
        
        
        
    }//GEN-LAST:event_txtUserNameClieKeyTyped

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
               MenuUI mm = new MenuUI(); 
                mm.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        
        ClienteDAO s = new ClienteDAO(); 
        
        int telefono = s.buscarClientePorRut(txtRutCliente.getText()); 
        
        txtTelefonoClie.setText(String.valueOf(telefono));
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtRutClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutClienteKeyReleased
        habilitarBotonGuardarCli();
        habilitarbotonEliminar();
    }//GEN-LAST:event_txtRutClienteKeyReleased

    private void txtNombreClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreClienteKeyReleased
      habilitarBotonGuardarCli();
      habilitarbotonEditar();
    }//GEN-LAST:event_txtNombreClienteKeyReleased

    private void txtApellidoClienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoClienKeyReleased
       habilitarBotonGuardarCli();
       habilitarbotonEditar();
    }//GEN-LAST:event_txtApellidoClienKeyReleased

    private void txtDireccionClieKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionClieKeyReleased
        habilitarBotonGuardarCli();
        habilitarbotonEditar();
    }//GEN-LAST:event_txtDireccionClieKeyReleased

    private void txtCorreoClienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoClienKeyReleased
        habilitarBotonGuardarCli();
        habilitarbotonEditar();
    }//GEN-LAST:event_txtCorreoClienKeyReleased

    private void txtTelefonoClieKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoClieKeyReleased
       habilitarBotonGuardarCli();
       habilitarbotonEditar();
    }//GEN-LAST:event_txtTelefonoClieKeyReleased

    private void txtUserNameClieKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameClieKeyReleased
        habilitarBotonGuardarCli();
        habilitarbotonEditar();
    }//GEN-LAST:event_txtUserNameClieKeyReleased

    private void txtPassClieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassClieKeyPressed
        habilitarBotonGuardarCli();
        habilitarbotonEditar();
    }//GEN-LAST:event_txtPassClieKeyPressed

    private void txtFiltrarporNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltrarporNombreKeyTyped
       
       txtFiltrarporNombre.addKeyListener(new KeyAdapter()
       {
           @Override
           public void keyTyped(KeyEvent e) {
              
               
               trs.setRowFilter(RowFilter.regexFilter("(?i)"+ txtFiltrarporNombre.getText(),1));
           }
           
       });
       
       trs = new TableRowSorter(tablaClientes.getModel()); 
       tablaClientes.setRowSorter(trs);
        
        
    }//GEN-LAST:event_txtFiltrarporNombreKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarClienteVehiculoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarClienteVehiculoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarClienteVehiculoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarClienteVehiculoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarClienteVehiculoUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrarClienVehi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTextField txtApellidoClien;
    private javax.swing.JTextField txtCorreoClien;
    private javax.swing.JTextField txtDireccionClie;
    private javax.swing.JTextField txtFiltrarporNombre;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtPassClie;
    private javax.swing.JTextField txtRutCliente;
    private javax.swing.JTextField txtTelefonoClie;
    private javax.swing.JTextField txtUserNameClie;
    // End of variables declaration//GEN-END:variables
}
