/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.MessageFormat;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pablo
 */
public class FacturaUI extends javax.swing.JFrame {

    /**
     * Creates new form FacturaUI
     */
    public FacturaUI() {
        initComponents();
        setLocationRelativeTo(null);
         setIconImage(new ImageIcon(getClass().getResource("/Imagenes/logoServi2.png")).getImage());
         
         TexteArea.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        panelToPrint = new javax.swing.JPanel();
        LabelLogo = new javax.swing.JLabel();
        LabelTexto1 = new javax.swing.JLabel();
        LabelTexto2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TexteArea = new javax.swing.JTextArea();
        printRecordBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LabelTotalFactura = new javax.swing.JLabel();
        LabelTotalFINAL = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        LabelNumeroDeFactura = new javax.swing.JLabel();
        LabelFechaFactura = new javax.swing.JLabel();
        LabelTipoPagoFac = new javax.swing.JLabel();
        LabelTotalProductos = new javax.swing.JLabel();
        LabelNeto = new javax.swing.JLabel();
        LabelIVA = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("$");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelToPrint.setBackground(new java.awt.Color(204, 204, 204));

        LabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoF.png"))); // NOI18N

        LabelTexto1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelTexto1.setForeground(new java.awt.Color(0, 0, 0));
        LabelTexto1.setText("Direccion: Arturo Pérez Canto ");

        LabelTexto2.setBackground(new java.awt.Color(255, 255, 255));
        LabelTexto2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelTexto2.setForeground(new java.awt.Color(0, 0, 0));
        LabelTexto2.setText("123, Curanilahue BIO-BIO, Chile ");

        TexteArea.setColumns(20);
        TexteArea.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TexteArea.setForeground(new java.awt.Color(255, 0, 0));
        TexteArea.setRows(5);
        TexteArea.setText("RUT: 87.214.523-8\nFACTURA ELECTRONICA\nTALLER MECÁNICO SERVIEXPRES\n");
        TexteArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jScrollPane1.setViewportView(TexteArea);

        printRecordBtn.setText("Generar PDF");
        printRecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printRecordBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Total Servicio: ");

        LabelTotalFactura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelTotalFactura.setForeground(new java.awt.Color(255, 0, 0));
        LabelTotalFactura.setText("LabelTotalServicios");

        LabelTotalFINAL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelTotalFINAL.setForeground(new java.awt.Color(255, 0, 0));
        LabelTotalFINAL.setText("LabelTotalFinal");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("FACTURA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fecha de Factura: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Numero de Factura");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Neto: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Iva: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Tipo de Pago:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Total de Productos Usados: ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Total: ");

        LabelNumeroDeFactura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelNumeroDeFactura.setForeground(new java.awt.Color(255, 0, 0));
        LabelNumeroDeFactura.setText("LabelNumeroFac");

        LabelFechaFactura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelFechaFactura.setForeground(new java.awt.Color(255, 0, 0));
        LabelFechaFactura.setText("LabelFechFactura");

        LabelTipoPagoFac.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelTipoPagoFac.setForeground(new java.awt.Color(255, 0, 0));
        LabelTipoPagoFac.setText("LabelTipoPago");

        LabelTotalProductos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelTotalProductos.setForeground(new java.awt.Color(255, 0, 0));
        LabelTotalProductos.setText("LabelTotalProductos");

        LabelNeto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelNeto.setForeground(new java.awt.Color(255, 0, 0));
        LabelNeto.setText("LabelNeto");

        LabelIVA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelIVA.setForeground(new java.awt.Color(255, 0, 0));
        LabelIVA.setText("LabelIVA");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_exit_40px_1_1.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("$");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("$");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("$");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("$");

        javax.swing.GroupLayout panelToPrintLayout = new javax.swing.GroupLayout(panelToPrint);
        panelToPrint.setLayout(panelToPrintLayout);
        panelToPrintLayout.setHorizontalGroup(
            panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelToPrintLayout.createSequentialGroup()
                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelToPrintLayout.createSequentialGroup()
                        .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelToPrintLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(LabelLogo))
                            .addGroup(panelToPrintLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelToPrintLayout.createSequentialGroup()
                                        .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelNumeroDeFactura)
                                            .addComponent(LabelFechaFactura)
                                            .addComponent(LabelTipoPagoFac)))))
                            .addGroup(panelToPrintLayout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelTexto2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelTexto1)))
                    .addGroup(panelToPrintLayout.createSequentialGroup()
                        .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelToPrintLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                                    .addComponent(jSeparator2)))
                            .addGroup(panelToPrintLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelToPrintLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LabelIVA))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelToPrintLayout.createSequentialGroup()
                                        .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelToPrintLayout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(LabelTotalFINAL))
                                            .addGroup(panelToPrintLayout.createSequentialGroup()
                                                .addGap(65, 65, 65)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(LabelNeto))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelToPrintLayout.createSequentialGroup()
                                        .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(panelToPrintLayout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panelToPrintLayout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(LabelTotalProductos)
                                            .addComponent(LabelTotalFactura))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(31, 31, 31))
            .addGroup(panelToPrintLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(170, 170, 170)
                .addComponent(printRecordBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelToPrintLayout.setVerticalGroup(
            panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelToPrintLayout.createSequentialGroup()
                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelToPrintLayout.createSequentialGroup()
                        .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelToPrintLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LabelLogo))
                            .addGroup(panelToPrintLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelTexto2))
                    .addGroup(panelToPrintLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LabelNumeroDeFactura))
                .addGap(10, 10, 10)
                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LabelFechaFactura))
                .addGap(11, 11, 11)
                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(LabelTipoPagoFac))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LabelTotalFactura)
                    .addComponent(jLabel15))
                .addGap(25, 25, 25)
                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(LabelTotalProductos)
                    .addComponent(jLabel13))
                .addGap(28, 28, 28)
                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNeto)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(25, 25, 25)
                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(LabelIVA))
                .addGap(30, 30, 30)
                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(LabelTotalFINAL)
                    .addComponent(jLabel10))
                .addGap(22, 22, 22)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(printRecordBtn))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelToPrint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelToPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        MenuUI a = new MenuUI();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void printRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printRecordBtnActionPerformed

        printRecord(panelToPrint);
    }//GEN-LAST:event_printRecordBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacturaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel LabelFechaFactura;
    public static javax.swing.JLabel LabelIVA;
    private javax.swing.JLabel LabelLogo;
    public static javax.swing.JLabel LabelNeto;
    public static javax.swing.JLabel LabelNumeroDeFactura;
    private javax.swing.JLabel LabelTexto1;
    private javax.swing.JLabel LabelTexto2;
    public static javax.swing.JLabel LabelTipoPagoFac;
    public static javax.swing.JLabel LabelTotalFINAL;
    public static javax.swing.JLabel LabelTotalFactura;
    public static javax.swing.JLabel LabelTotalProductos;
    private javax.swing.JTextArea TexteArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public static javax.swing.JPanel panelToPrint;
    private javax.swing.JButton printRecordBtn;
    // End of variables declaration//GEN-END:variables

private void printRecord(JPanel panel)
{
    PrinterJob printerJob = PrinterJob.getPrinterJob(); 
    
    printerJob.setJobName("Print Record");
    
    printerJob.setPrintable(new Printable() 
    {
        @Override
        public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
            
            if(pageIndex > 0){
                return Printable.NO_SUCH_PAGE;
            }
            
            Graphics2D graphics2D = (Graphics2D)graphics; 
            
            graphics2D.translate(pageFormat.getImageableX()*5, pageFormat.getImageableY()*5);
            
            graphics2D.scale(1.2, 1.2);
            
            panel.paint(graphics2D);
            
            return Printable.PAGE_EXISTS; 
            
            
        }
     
    });
    
    boolean returningResult = printerJob.printDialog(); 
    
    if(returningResult)
    {
        try {
            printerJob.print();
        } catch (PrinterException printerException) {
            JOptionPane.showMessageDialog(this, "Print Error:" + printerException.getMessage());
        }
    }
}


}
