/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CONTROLADOR.FamiliaDAO;
import MODELO.Familia;
import NEGOCIO.productoNegocio;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pablo
 */
public class FamiliaUI extends javax.swing.JFrame {

    /**
     * Creates new form FamiliaUI
     */
    
    private productoNegocio ebo = new productoNegocio();
    
    public FamiliaUI() {
        initComponents();
        setLocationRelativeTo(null);
        idMax();
        ListarFamilias();
        cerrar();
        txtIDcodigoFamilia.setEditable(false);
        
         setIconImage(new ImageIcon(getClass().getResource("/Imagenes/logoServi2.png")).getImage());
         
         btnGuardarFamilia.setEnabled(false);
         btnEliminarFamilia.setEnabled(false);
         btnEditarFamilia.setEnabled(false);
    }
    
      public void cerrar()
    {
        try {
            
                this.setDefaultCloseOperation(AgregarClienteVehiculoUI.DO_NOTHING_ON_CLOSE);
                addWindowListener(new WindowAdapter() {
                    public void windowClosing(WindowEvent e){
                        confirmarSalida();
                    }
                });
                this.setVisible(true);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
      
     public void confirmarSalida()
    {
        int valor= JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea cerrar la apliación Serviexpress?","Advertencia", JOptionPane.YES_NO_OPTION);
        if(valor==JOptionPane.YES_OPTION)
        {
            JOptionPane.showMessageDialog(null,"Gracias, hasta pronto","Gracias",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }
    
    
    
    public void ListarFamilias()
    {
        FamiliaDAO daoF = new FamiliaDAO(); 
        TablaFamilia.setModel(daoF.listarFamilia());
        
        
    }
    
    public void LimpiarFamilia()
    {
        txtIDcodigoFamilia.setText("");
        txtNombreFamilia.setText("");
        
        idMax();
        
        
    }
    
    public void idMax()
    {
        txtIDcodigoFamilia.setText(ebo.getMaxFamiliaID()+"");
        
        
    }
    
    public void habilitarBotonGuardarFamilia()
    {
        if(!txtIDcodigoFamilia.getText().isEmpty() && !txtNombreFamilia.getText().isEmpty())
        {
            btnGuardarFamilia.setEnabled(true);
        }
        else
        {
            btnGuardarFamilia.setEnabled(false);
        }
        
        
    }
    
    public void habilitarBotonEditarFamilia()
    {
           if(!txtIDcodigoFamilia.getText().isEmpty() && !txtNombreFamilia.getText().isEmpty())
        {
            btnEditarFamilia.setEnabled(true);
        }
        else
        {
           btnEditarFamilia.setEnabled(false);
        }
    }
    
    public void habilitarBotonEliminarFamilia()
    {
           if(!txtIDcodigoFamilia.getText().isEmpty() && !txtNombreFamilia.getText().isEmpty())
        {
            btnEliminarFamilia.setEnabled(true);
        }
        else
        {
            btnEliminarFamilia.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaFamilia = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIDcodigoFamilia = new javax.swing.JTextField();
        txtNombreFamilia = new javax.swing.JTextField();
        btnGuardarFamilia = new javax.swing.JButton();
        btnEditarFamilia = new javax.swing.JButton();
        btnEliminarFamilia = new javax.swing.JButton();
        btnLimpiarDatosFamilia = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Familia Producto ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 20, -1, -1));

        TablaFamilia.setBackground(new java.awt.Color(102, 255, 102));
        TablaFamilia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        TablaFamilia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TablaFamilia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaFamilia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaFamiliaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaFamilia);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 379, 111));

        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_exit_40px_1.png"))); // NOI18N
        jLabel10.setText("Salir");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 65, 448, 7));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo Familia: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre familia: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        txtIDcodigoFamilia.setBackground(new java.awt.Color(102, 255, 204));
        txtIDcodigoFamilia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIDcodigoFamilia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        txtIDcodigoFamilia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDcodigoFamiliaKeyReleased(evt);
            }
        });
        jPanel1.add(txtIDcodigoFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 32, -1));

        txtNombreFamilia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNombreFamilia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        txtNombreFamilia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreFamiliaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreFamiliaKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombreFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 132, -1));

        btnGuardarFamilia.setBackground(new java.awt.Color(102, 102, 255));
        btnGuardarFamilia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardarFamilia.setText("Registrar");
        btnGuardarFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarFamiliaActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        btnEditarFamilia.setBackground(new java.awt.Color(102, 102, 255));
        btnEditarFamilia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditarFamilia.setText("Actualizar");
        btnEditarFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarFamiliaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 110, -1));

        btnEliminarFamilia.setBackground(new java.awt.Color(102, 102, 255));
        btnEliminarFamilia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminarFamilia.setText("Eliminar");
        btnEliminarFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFamiliaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 130, 100, -1));

        btnLimpiarDatosFamilia.setBackground(new java.awt.Color(102, 102, 255));
        btnLimpiarDatosFamilia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpiarDatosFamilia.setText("Nuevo");
        btnLimpiarDatosFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarDatosFamiliaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiarDatosFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Familia Producto ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        ModuloBodegaUI mm = new ModuloBodegaUI();
        mm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void TablaFamiliaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaFamiliaMouseClicked
        
        
        int seleccion = TablaFamilia.rowAtPoint(evt.getPoint()); 
        
        txtIDcodigoFamilia.setText(TablaFamilia.getValueAt(seleccion, 0)+"");
        txtNombreFamilia.setText(TablaFamilia.getValueAt(seleccion, 1)+"");
        
        habilitarBotonEditarFamilia();
        habilitarBotonEliminarFamilia();
        
    }//GEN-LAST:event_TablaFamiliaMouseClicked

    private void btnGuardarFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarFamiliaActionPerformed
      
          int i = JOptionPane.showConfirmDialog(this, "¿Estas seguro que deseas Registrar una nueva Familia de Productos?"); 
          if(i==0){
              
              if(txtIDcodigoFamilia.getText().isEmpty() || 
                      txtNombreFamilia.getText().isEmpty()) 
              {
                  JOptionPane.showMessageDialog(null, "Llene todos los campos");
              }
              else
              {
                  Familia modelF = new Familia(); 
                  FamiliaDAO daoF = new FamiliaDAO(); 
                  
                  modelF.setCodFamilia(Integer.parseInt(txtIDcodigoFamilia.getText()));
                  modelF.setNombreFamilia(txtNombreFamilia.getText());
                  
                  if(daoF.registroFamilia(modelF))
                  {
                      JOptionPane.showMessageDialog(null, "Se registro la Nueva Familia con exito");
                      ListarFamilias();
                      LimpiarFamilia();
                      habilitarBotonGuardarFamilia();
                     
                      
                  }
                  
                  
              }
                  
              
              
              
          } else if(i==1){
              
              JOptionPane.showMessageDialog(this, "Se cancelo el registro de la Familia del Producto");
              
              
          }
        
        
        
    }//GEN-LAST:event_btnGuardarFamiliaActionPerformed

    private void btnLimpiarDatosFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarDatosFamiliaActionPerformed
        
        LimpiarFamilia(); 
        
    }//GEN-LAST:event_btnLimpiarDatosFamiliaActionPerformed

    private void btnEditarFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarFamiliaActionPerformed
      
            int i = JOptionPane.showConfirmDialog(this, "¿Estas seguro que deseas actualizar los datos de la Familia?"); 
            if(i==0)
            {
                
                if(txtIDcodigoFamilia.getText().isEmpty())
                {
                    String mensaje = "Debe tener un codigoc seleccionado";
                    JOptionPane.showMessageDialog(null, mensaje);
                }
                else
                {
                  Familia modelF = new Familia(); 
                  FamiliaDAO daoF = new FamiliaDAO(); 
                  
                  modelF.setCodFamilia(Integer.parseInt(txtIDcodigoFamilia.getText()));
                  modelF.setNombreFamilia(txtNombreFamilia.getText());
                  
                 daoF.ModificarFamilia(modelF); 
                 
                 String mensaje = "Nombre de Familia Actualizado con exito"; 
                 ListarFamilias();
                 habilitarBotonEditarFamilia();
                    
                    
                }
                
                
                
            }else if(i==1)
            {
                  JOptionPane.showMessageDialog(this, "Se cancelo la actualizacion de datos de la Familia de Productos");
            }
        
        
    }//GEN-LAST:event_btnEditarFamiliaActionPerformed

    private void btnEliminarFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFamiliaActionPerformed
    
          int i = JOptionPane.showConfirmDialog(this, "¿Estas seguro que deseas eliminar la familia?"); 
          if(i==0){
              
                  Familia modelF = new Familia(); 
                  FamiliaDAO daoF = new FamiliaDAO(); 
                  
                  modelF.setCodFamilia(Integer.parseInt(txtIDcodigoFamilia.getText()));
                  modelF.setNombreFamilia(txtNombreFamilia.getText());
                  
                  if(daoF.eliminarFamilia(modelF))
                  {
                      JOptionPane.showMessageDialog(null, "Se Elimino la Familia con exito");
                      ListarFamilias();
                      LimpiarFamilia();
                      habilitarBotonEliminarFamilia();
                  }
              
              
              
          }else if(i==1)
          {
                JOptionPane.showMessageDialog(this, "Se cancelo la eliminacion de la familia de productos");
          }
        
        
        
    }//GEN-LAST:event_btnEliminarFamiliaActionPerformed

    private void txtIDcodigoFamiliaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDcodigoFamiliaKeyReleased
        
        habilitarBotonGuardarFamilia();
        habilitarBotonEliminarFamilia();
        
    }//GEN-LAST:event_txtIDcodigoFamiliaKeyReleased

    private void txtNombreFamiliaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreFamiliaKeyReleased
        habilitarBotonEditarFamilia();
        habilitarBotonGuardarFamilia();
    }//GEN-LAST:event_txtNombreFamiliaKeyReleased

    private void txtNombreFamiliaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreFamiliaKeyTyped
        
        
       int numerocaracteres = 30; 
        
        if(txtNombreFamilia.getText().length() >= numerocaracteres) {
            evt.consume();
   
            JOptionPane.showMessageDialog(rootPane, "El nombre de familia no puede contener mas de 30 caracteres");
        }
        
        
    }//GEN-LAST:event_txtNombreFamiliaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FamiliaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FamiliaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FamiliaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FamiliaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FamiliaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaFamilia;
    private javax.swing.JButton btnEditarFamilia;
    private javax.swing.JButton btnEliminarFamilia;
    private javax.swing.JButton btnGuardarFamilia;
    private javax.swing.JButton btnLimpiarDatosFamilia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtIDcodigoFamilia;
    private javax.swing.JTextField txtNombreFamilia;
    // End of variables declaration//GEN-END:variables
}
