/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CONTROLADOR.ReservaDAO;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author pablo
 */
public class ListadoReservasUI extends javax.swing.JFrame {

     TableRowSorter trs;
    
    /**
     * Creates new form ListadoReservasUI
     */
    public ListadoReservasUI() {
        initComponents();
        ListarReserva();
        setLocationRelativeTo(null);
        cerrar();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/logoServi2.png")).getImage());
        
        txtCodigoReservaListado.setEditable(false);
        txtHoraReserva.setEditable(false);
        txtPatenteVehiculo.setEditable(false);
        txtRutDueño.setEditable(false);
        txtMecanicoReserva.setEditable(false);
        txtFechaReserva.setEditable(false);
        txtEstadoReserva.setEditable(false);
        
        
        btnRealizarServicioYenviar.setEnabled(false);
    }
    
       public void ListarReserva()
    {
        ReservaDAO dd = new ReservaDAO(); 
        TablaOrdenesActualess.setModel(dd.listarReservas());
    }
       
         public void cerrar()
    {
        try {
            
                this.setDefaultCloseOperation(AgregarClienteVehiculoUI.DO_NOTHING_ON_CLOSE);
                addWindowListener(new WindowAdapter() {
                    public void windowClosing(WindowEvent e){
                        confirmarSalida();
                    }
                });
                this.setVisible(true);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
      
     public void confirmarSalida()
    {
        int valor= JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea cerrar la apliación Serviexpress?","Advertencia", JOptionPane.YES_NO_OPTION);
        if(valor==JOptionPane.YES_OPTION)
        {
            JOptionPane.showMessageDialog(null,"Gracias, hasta pronto","Gracias",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }
     
     
    public void habilitarbtnGuardar()
    {
        if(!txtCodigoReservaListado.getText().isEmpty() && 
              !txtPatenteVehiculo.getText().isEmpty() && 
               !txtRutDueño.getText().isEmpty())
        {
            btnRealizarServicioYenviar.setEnabled(true);
        }
        else
        {
            btnRealizarServicioYenviar.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaOrdenesActualess = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoReservaListado = new javax.swing.JTextField();
        btnRealizarServicioYenviar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPatenteVehiculo = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        txtRutDueño = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMecanicoReserva = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHoraReserva = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFechaReserva = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEstadoReserva = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFiltrarPatente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanel1KeyReleased(evt);
            }
        });

        TablaOrdenesActualess.setBackground(new java.awt.Color(102, 255, 102));
        TablaOrdenesActualess.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        TablaOrdenesActualess.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TablaOrdenesActualess.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaOrdenesActualess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaOrdenesActualessMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TablaOrdenesActualess);

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_exit_40px_1.png"))); // NOI18N
        jLabel8.setText("Salir");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Reservas Realizadas");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo Reserva: ");

        txtCodigoReservaListado.setBackground(new java.awt.Color(102, 255, 204));
        txtCodigoReservaListado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCodigoReservaListado.setToolTipText("Codigo de reserva");
        txtCodigoReservaListado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));

        btnRealizarServicioYenviar.setBackground(new java.awt.Color(102, 102, 255));
        btnRealizarServicioYenviar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRealizarServicioYenviar.setText("Ejecutar Servicio ");
        btnRealizarServicioYenviar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        btnRealizarServicioYenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarServicioYenviarActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Patente: ");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rut Dueño: ");

        txtPatenteVehiculo.setBackground(new java.awt.Color(102, 255, 204));
        txtPatenteVehiculo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPatenteVehiculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        txtPatenteVehiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPatenteVehiculoKeyReleased(evt);
            }
        });

        txtRutDueño.setBackground(new java.awt.Color(102, 255, 204));
        txtRutDueño.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtRutDueño.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        txtRutDueño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRutDueñoKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mecánico a cargo ");

        txtMecanicoReserva.setBackground(new java.awt.Color(102, 255, 204));
        txtMecanicoReserva.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hora Reservada: ");

        txtHoraReserva.setBackground(new java.awt.Color(102, 255, 204));
        txtHoraReserva.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha Reservada: ");

        txtFechaReserva.setBackground(new java.awt.Color(102, 255, 204));
        txtFechaReserva.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Estado Reserva:");

        txtEstadoReserva.setBackground(new java.awt.Color(102, 255, 204));
        txtEstadoReserva.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEstadoReserva.setToolTipText("si es numero 0, pendiete, numero 1 esta pagado");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Filtrar por patente:");

        txtFiltrarPatente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtFiltrarPatente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        txtFiltrarPatente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiltrarPatenteKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCodigoReservaListado)
                                    .addComponent(txtPatenteVehiculo)
                                    .addComponent(txtRutDueño))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMecanicoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel7)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtHoraReserva, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                            .addComponent(txtFechaReserva)
                                            .addComponent(txtEstadoReserva)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(247, 247, 247)
                                        .addComponent(jLabel9)
                                        .addGap(150, 150, 150)
                                        .addComponent(jLabel8)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 1, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(btnRealizarServicioYenviar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFiltrarPatente, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoReservaListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtMecanicoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPatenteVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtHoraReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRutDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtFechaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtEstadoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btnRealizarServicioYenviar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFiltrarPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaOrdenesActualessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaOrdenesActualessMouseClicked

     //   SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy", Locale.getDefault());
       // String date = formato.format(FECHADateCalendar.getDate());

        int seleccion = TablaOrdenesActualess.rowAtPoint(evt.getPoint());

        txtCodigoReservaListado.setText(TablaOrdenesActualess.getValueAt(seleccion, 0)+"");
        txtFechaReserva.setText(TablaOrdenesActualess.getValueAt(seleccion,1)+"");
        txtPatenteVehiculo.setText(TablaOrdenesActualess.getValueAt(seleccion, 2)+"");
        txtRutDueño.setText(TablaOrdenesActualess.getValueAt(seleccion, 3)+"");
        txtEstadoReserva.setText(TablaOrdenesActualess.getValueAt(seleccion, 4)+"");
        txtHoraReserva.setText(TablaOrdenesActualess.getValueAt(seleccion, 5)+"");
        txtMecanicoReserva.setText(TablaOrdenesActualess.getValueAt(seleccion, 6)+"");
        
        
        
        habilitarbtnGuardar();
    }//GEN-LAST:event_TablaOrdenesActualessMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        
    
            ModuloReservaUI s = new ModuloReservaUI();
            s.setVisible(true);
            this.setVisible(false);
        
    

    }//GEN-LAST:event_jLabel8MouseClicked

    private void btnRealizarServicioYenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarServicioYenviarActionPerformed

         int i = JOptionPane.showConfirmDialog(this, "¿Estas seguro que hacer la ejecución de esta reserva?"); 
       
        if(i==0)
        {
          
        ModuloEjecucionUI a = new ModuloEjecucionUI();
        a.setVisible(true);
        this.setVisible(false);
        
        String info = txtCodigoReservaListado.getText(); 
        ModuloEjecucionUI.txtCodigoreal.setText(info);
        
        String info2 = txtHoraReserva.getText();
        ModuloEjecucionUI.txtHoraEjecucion.setText(info2);
        
        String info3 = txtPatenteVehiculo.getText(); 
        ModuloEjecucionUI.txtPatenteEnEjecucion.setText(info3);
          
        String info4 = txtRutDueño.getText(); 
        ModuloEjecucionUI.txtRUTEJECUCION.setText(info4);
        
        String info5 = txtMecanicoReserva.getText(); 
        ModuloEjecucionUI.txtMecEje.setText(info5);
        
        
            
        }
        else if(i==1){
            
            JOptionPane.showMessageDialog(this, "Se cancelo el proceso de ejecución");
            
        }


        
     
        
        
        
        
    }//GEN-LAST:event_btnRealizarServicioYenviarActionPerformed

    private void jPanel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyReleased
        habilitarbtnGuardar();
    }//GEN-LAST:event_jPanel1KeyReleased

    private void txtPatenteVehiculoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatenteVehiculoKeyReleased
       habilitarbtnGuardar();
    }//GEN-LAST:event_txtPatenteVehiculoKeyReleased

    private void txtRutDueñoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutDueñoKeyReleased
        habilitarbtnGuardar();
    }//GEN-LAST:event_txtRutDueñoKeyReleased

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
       // habilitarbtnGuardar();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void txtFiltrarPatenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltrarPatenteKeyTyped
     
        txtFiltrarPatente.addKeyListener(new KeyAdapter()
        {
            @Override
            public void keyTyped(KeyEvent e) {
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtFiltrarPatente.getText(),2));
            }
             
        });
        
        trs = new TableRowSorter(TablaOrdenesActualess.getModel()); 
        TablaOrdenesActualess.setRowSorter(trs);
        
        
    }//GEN-LAST:event_txtFiltrarPatenteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoReservasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoReservasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoReservasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoReservasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListadoReservasUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaOrdenesActualess;
    private javax.swing.JButton btnRealizarServicioYenviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtCodigoReservaListado;
    private javax.swing.JTextField txtEstadoReserva;
    private javax.swing.JTextField txtFechaReserva;
    private javax.swing.JTextField txtFiltrarPatente;
    private javax.swing.JTextField txtHoraReserva;
    private javax.swing.JTextField txtMecanicoReserva;
    private javax.swing.JTextField txtPatenteVehiculo;
    private javax.swing.JTextField txtRutDueño;
    // End of variables declaration//GEN-END:variables
}
