/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CONTROLADOR.ServicioDAO;
import MODELO.Servicio;
import NEGOCIO.servicioNegocio;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pablo
 */
public class ModuloServiciosUI extends javax.swing.JFrame {

    /**
     * Creates new form ModuloServiciosUI
     */
    
    ServicioDAO servi = new ServicioDAO(); 
    
    private servicioNegocio ss = new servicioNegocio();
    
    public ModuloServiciosUI() {
        initComponents();
        setLocationRelativeTo(null);
        cerrar();
        ListarServicios();
        idMax();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/logoServi2.png")).getImage());
        txtCodigoServi.setEditable(false);
        btnAgregarServi.setEnabled(false);
        btnEditarActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
        
    }
    
    public void habilitarBotonGuardar()
    {
        if(!txtCodigoServi.getText().isEmpty() && 
            !txtNombreServicio.getText().isEmpty() && 
              !txtPrecioServi.getText().isEmpty())
        {
            btnAgregarServi.setEnabled(true);
        }
        else
        {
            btnAgregarServi.setEnabled(false);
        }
    }
    
      public void habilitarBotonEditar()
    {
        if(!txtCodigoServi.getText().isEmpty() && 
            !txtNombreServicio.getText().isEmpty() && 
              !txtPrecioServi.getText().isEmpty())
        {
            btnEditarActualizar.setEnabled(true);
        }
        else
        {
            btnEditarActualizar.setEnabled(false);
        }
    }
      
        public void habilitarBotonEliminar()
    {
        if(!txtCodigoServi.getText().isEmpty() && 
            !txtNombreServicio.getText().isEmpty() && 
              !txtPrecioServi.getText().isEmpty())
        {
            btnEliminar.setEnabled(true);
        }
        else
        {
            btnEliminar.setEnabled(false);
        }
    }
    
    private void ListarServicios()
    {
        ServicioDAO daoS = new ServicioDAO(); 
        TablaListarServicios.setModel(daoS.listarServicios());
    }
    
    public void idMax()
    {
        txtCodigoServi.setText(ss.getMaxID()+"");
    }
    
    public void LimpiarServicios()
    {
        txtCodigoServi.setText("");
        txtNombreServicio.setText("");
        txtPrecioServi.setText("");
        
        idMax();
    }
    
    public void cerrar()
    {
        try {
            
                this.setDefaultCloseOperation(AgregarClienteVehiculoUI.DO_NOTHING_ON_CLOSE);
                addWindowListener(new WindowAdapter() {
                    public void windowClosing(WindowEvent e){
                        confirmarSalida();
                    }
                });
                this.setVisible(true);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
      
     public void confirmarSalida()
    {
        int valor= JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea cerrar la apliación Serviexpress?","Advertencia", JOptionPane.YES_NO_OPTION);
        if(valor==JOptionPane.YES_OPTION)
        {
            JOptionPane.showMessageDialog(null,"Gracias, hasta pronto","Gracias",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaListarServicios = new javax.swing.JTable();
        txtCodigoServi = new javax.swing.JTextField();
        txtPrecioServi = new javax.swing.JTextField();
        txtNombreServicio = new javax.swing.JTextField();
        btnAgregarServi = new javax.swing.JButton();
        btnNuevoLimpiar = new javax.swing.JButton();
        btnEditarActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Servicios ServiExpress");

        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_exit_40px_1.png"))); // NOI18N
        jLabel10.setText("Salir");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Codigo de Servicio: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Nombre del Servicio: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Precio: ");

        TablaListarServicios.setBackground(new java.awt.Color(102, 255, 102));
        TablaListarServicios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        TablaListarServicios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TablaListarServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaListarServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaListarServiciosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaListarServicios);

        txtCodigoServi.setBackground(new java.awt.Color(102, 255, 204));
        txtCodigoServi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCodigoServi.setToolTipText("Codigo Servicio Automatico ");
        txtCodigoServi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoServiKeyReleased(evt);
            }
        });

        txtPrecioServi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPrecioServi.setToolTipText("Valor del Servicio");
        txtPrecioServi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        txtPrecioServi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecioServiKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioServiKeyTyped(evt);
            }
        });

        txtNombreServicio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNombreServicio.setToolTipText("Nombre Del Servicio ");
        txtNombreServicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        txtNombreServicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreServicioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreServicioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreServicioKeyTyped(evt);
            }
        });

        btnAgregarServi.setBackground(new java.awt.Color(102, 102, 255));
        btnAgregarServi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregarServi.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarServi.setText("Registrar");
        btnAgregarServi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        btnAgregarServi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarServiActionPerformed(evt);
            }
        });

        btnNuevoLimpiar.setBackground(new java.awt.Color(102, 102, 255));
        btnNuevoLimpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNuevoLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoLimpiar.setText("Nuevo");
        btnNuevoLimpiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        btnNuevoLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoLimpiarActionPerformed(evt);
            }
        });

        btnEditarActualizar.setBackground(new java.awt.Color(102, 102, 255));
        btnEditarActualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditarActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarActualizar.setText("Actualizar");
        btnEditarActualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        btnEditarActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(102, 102, 255));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnNuevoLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditarActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNombreServicio))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCodigoServi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(jLabel4)
                            .addGap(3, 3, 3)
                            .addComponent(txtPrecioServi, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(btnAgregarServi, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigoServi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrecioServi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarServi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnNuevoLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditarActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
       VistaPrueba2UI a = new VistaPrueba2UI(); 
       a.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void btnAgregarServiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarServiActionPerformed
        
          int i = JOptionPane.showConfirmDialog(this, "¿Estas seguro que deseas Registrar este Servicio"); 
          if(i==0){
              
              if(txtCodigoServi.getText().isEmpty() ||
                  txtNombreServicio.getText().isEmpty() ||
                      txtPrecioServi.getText().isEmpty()) 
              {
                  JOptionPane.showMessageDialog(null, "Llene todos los campos");
              }
              else{
                  
                  Servicio modelS = new Servicio(); 
                  ServicioDAO daoS = new ServicioDAO(); 
                  
                  modelS.setCodServicio(Integer.parseInt(txtCodigoServi.getText()));
                  modelS.setNombreServicio(txtNombreServicio.getText());
                  modelS.setPrecioServicio(Integer.parseInt(txtPrecioServi.getText()));
                  
                  if(daoS.registroServicio(modelS))
                  {
                      JOptionPane.showMessageDialog(null, "Se registro al Servicio con exito");
                      ListarServicios();
                      LimpiarServicios();
                      habilitarBotonGuardar();
                  }
              }
                      
              
              
          
          
              
          }else if(i==0)
          {
               JOptionPane.showMessageDialog(this, "Se cancelo el registro del Servicio");
          }
        
        
    }//GEN-LAST:event_btnAgregarServiActionPerformed

    private void TablaListarServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaListarServiciosMouseClicked
        
        int seleccion = TablaListarServicios.rowAtPoint(evt.getPoint()); 
        
        txtCodigoServi.setText(TablaListarServicios.getValueAt(seleccion, 0)+"");
        txtNombreServicio.setText(TablaListarServicios.getValueAt(seleccion, 1)+"");
        txtPrecioServi.setText(TablaListarServicios.getValueAt(seleccion, 2)+"");
        
        habilitarBotonEliminar();
        habilitarBotonEditar();
        
        
    }//GEN-LAST:event_TablaListarServiciosMouseClicked

    private void txtNombreServicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreServicioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreServicioKeyPressed

    private void txtNombreServicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreServicioKeyTyped
        
       int numerocaracteres = 80; 
        
        if(txtNombreServicio.getText().length() >= numerocaracteres) {
            evt.consume();
   
            JOptionPane.showMessageDialog(rootPane, "El Nombre no puede tener mas de 80 Caracteres");
        }
        
    }//GEN-LAST:event_txtNombreServicioKeyTyped

    private void txtPrecioServiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioServiKeyTyped
        
          char c = evt.getKeyChar(); 
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
        
        int numerocaracteres = 30; 
        
        if(txtPrecioServi.getText().length() >= numerocaracteres) {
            evt.consume();
   
            JOptionPane.showMessageDialog(rootPane, "El precio del Servicio es muy largo");
        }
        
        
        
    }//GEN-LAST:event_txtPrecioServiKeyTyped

    private void btnNuevoLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoLimpiarActionPerformed
        LimpiarServicios();
        habilitarBotonEditar();
        habilitarBotonEliminar();
        habilitarBotonGuardar();
   
    }//GEN-LAST:event_btnNuevoLimpiarActionPerformed

    private void btnEditarActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActualizarActionPerformed
        
        int i = JOptionPane.showConfirmDialog(this, "¿Estas seguro que deseas actualizar los datos del Servicio?"); 
            if(i==0) {
                
                if(txtCodigoServi.getText().isEmpty())
                {
                     String mensaje = "debe seleccionar un Codigo para editar"; 
                      JOptionPane.showMessageDialog(null, mensaje);
                }
                else{
                    
                  Servicio modelS = new Servicio(); 
                  ServicioDAO daoS = new ServicioDAO(); 
                  
                  modelS.setCodServicio(Integer.parseInt(txtCodigoServi.getText()));
                  modelS.setNombreServicio(txtNombreServicio.getText());
                  modelS.setPrecioServicio(Integer.parseInt(txtPrecioServi.getText()));
                  
                  if(daoS.ModificarServicio(modelS))
                  {
                      String mensaje = "Servicio Modificado con exito"; 
                      JOptionPane.showMessageDialog(null, mensaje);
                      ListarServicios();
                      habilitarBotonEditar();
                      
                  }
                    
                }
                
                
            }else if(i==1)
            {
                 JOptionPane.showMessageDialog(this, "Se cancelo la actualizacion de datos del Servicio");
            }
        
        
        
    }//GEN-LAST:event_btnEditarActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        int i = JOptionPane.showConfirmDialog(this, "¿Estas seguro que deseas eliminar el Servicio?"); 
       
        if(i==0){
         
                 
                  Servicio modelS = new Servicio(); 
                  ServicioDAO daoS = new ServicioDAO(); 
                  
                  modelS.setCodServicio(Integer.parseInt(txtCodigoServi.getText()));
                  modelS.setNombreServicio(txtNombreServicio.getText());
                  modelS.setPrecioServicio(Integer.parseInt(txtPrecioServi.getText()));
                  if(daoS.EliminarServicio(modelS))
                  {
                      JOptionPane.showMessageDialog(null, "Se Elimino al Servicio con exito");  
                      ListarServicios();
                      LimpiarServicios();
                      habilitarBotonEliminar();
                  }
            
            
        }else if(i==1)
        {
            JOptionPane.showMessageDialog(this, "Se cancelo la eliminacion del Servicio"); 
        }
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtCodigoServiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoServiKeyReleased
        habilitarBotonGuardar();
        habilitarBotonEliminar();
    }//GEN-LAST:event_txtCodigoServiKeyReleased

    private void txtPrecioServiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioServiKeyReleased
       habilitarBotonGuardar();
       habilitarBotonEditar();
    }//GEN-LAST:event_txtPrecioServiKeyReleased

    private void txtNombreServicioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreServicioKeyReleased
       habilitarBotonGuardar();
       habilitarBotonEditar();
    }//GEN-LAST:event_txtNombreServicioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloServiciosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloServiciosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloServiciosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloServiciosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuloServiciosUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaListarServicios;
    private javax.swing.JButton btnAgregarServi;
    private javax.swing.JButton btnEditarActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevoLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtCodigoServi;
    private javax.swing.JTextField txtNombreServicio;
    private javax.swing.JTextField txtPrecioServi;
    // End of variables declaration//GEN-END:variables
}
