/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CONTROLADOR.EjecucionDAO;
import CONTROLADOR.ReservaDAO;
import CONTROLADOR.ServicioDAO;
import MODELO.Ejecucion;
import MODELO.Servicio;
import NEGOCIO.servicioNegocio;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author pablo
 */
public class OrdenServicioUI extends javax.swing.JFrame {
    
    
    DefaultTableModel dm; 
    DefaultTableModel modelo; 
    /**
     * Creates new form OrdenServicioUI
     */
    
  //  DefaultTableModel modelo;
    
    ServicioDAO combo = new ServicioDAO(); 
    
    private TableRowSorter trsfiltro;
    String filtro;
    
    
    public OrdenServicioUI() {
        initComponents();
        
           txtFiltroIDReserva.addKeyListener(new KeyAdapter(){
            public void KeyReased(final KeyEvent e){
                String cadena = txtFiltroIDReserva.getText();
                txtFiltroIDReserva.setText(cadena);
                repaint();
                filtro();
            }
        });
       
        
    
        
        
        
        setLocationRelativeTo(null);
        listarServicio();
        txtTotalServiciosOrden.setText(Integer.toString(suma()));  
        
       
     //   combo.consultar_ReservaServicioRealizado(ComboCodigoDeActividad);
        
        
    
    }
        
       public void listarServicio(){
        
        ServicioDAO daoS = new ServicioDAO(); 
 //       tablaServiciosRealizados.setModel(daoS.listarServiciosRealizados());
          
    
    }
       

    public int suma()
    {
        int contar=tablaServiciosRealizados.getRowCount(); 
        int suma=0; 
        for(int i = 0; i < contar; i++){
            suma = suma+Integer.parseInt(tablaServiciosRealizados.getValueAt(i, 2).toString());
        }
        
        return suma; 
    }
    
    private void filtro(String consulta, JTable tabla)
    {
        dm = (DefaultTableModel)tablaServiciosRealizados.getModel();
        TableRowSorter<DefaultTableModel>tr = new TableRowSorter<>(dm); 
        
        tablaServiciosRealizados.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(consulta));
        
         txtTotalServiciosOrden.setText(Integer.toString(suma()));  
        
        
    }
    
    public void filtro()
    {
        filtro = txtFiltroIDReserva.getText(); 
        trsfiltro.setRowFilter(RowFilter.regexFilter(txtFiltroIDReserva.getText(),1));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaServiciosRealizados = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnEnviaradetalleFactura = new javax.swing.JButton();
        txtTotalServiciosOrden = new javax.swing.JTextField();
        ComboCodigoDeActividad = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnEliminarServicioRealizado = new javax.swing.JButton();
        txtEliminarActividad = new javax.swing.JTextField();
        txtFiltroIDReserva = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Actividades de Vehiculos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 70, 860, -1));

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_exit_40px_1.png"))); // NOI18N
        jLabel8.setText("Salir");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, -1));

        tablaServiciosRealizados.setBackground(new java.awt.Color(102, 255, 102));
        tablaServiciosRealizados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tablaServiciosRealizados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaServiciosRealizados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaServiciosRealizadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaServiciosRealizados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 710, 110));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo de Servicio Realizado ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        btnEnviaradetalleFactura.setText("Guardar en detalle de factura");
        btnEnviaradetalleFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviaradetalleFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnviaradetalleFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));
        jPanel1.add(txtTotalServiciosOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 110, -1));

        ComboCodigoDeActividad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ComboCodigoDeActividad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboCodigoDeActividadItemStateChanged(evt);
            }
        });
        ComboCodigoDeActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCodigoDeActividadActionPerformed(evt);
            }
        });
        jPanel1.add(ComboCodigoDeActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 140, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total a pagar: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        btnEliminarServicioRealizado.setText("Eliminar Actividad Realizada");
        btnEliminarServicioRealizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarServicioRealizadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarServicioRealizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, -1, -1));
        jPanel1.add(txtEliminarActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 140, -1));

        txtFiltroIDReserva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroIDReservaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiltroIDReservaKeyTyped(evt);
            }
        });
        jPanel1.add(txtFiltroIDReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 150, 20));

        jButton1.setText("Nueva Actividad ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
         
          MenuUI ss = new MenuUI(); 
          ss.setVisible(true);
          this.setVisible(false);
        
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void btnEnviaradetalleFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviaradetalleFacturaActionPerformed
        
        DetalleFacturaUI a = new DetalleFacturaUI(); 
        a.setVisible(true);
        String info = txtTotalServiciosOrden.getText(); 
        DetalleFacturaUI.txtTotalServiciosDetalle.setText(info);
        dispose();
        
        
    }//GEN-LAST:event_btnEnviaradetalleFacturaActionPerformed

    private void tablaServiciosRealizadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaServiciosRealizadosMouseClicked
      
        
        int seleccion = tablaServiciosRealizados.rowAtPoint(evt.getPoint()); 
        
        txtEliminarActividad.setText(tablaServiciosRealizados.getValueAt(seleccion, 0)+"");
        
        
        txtTotalServiciosOrden.setText(Integer.toString(suma()));  
        
        
    }//GEN-LAST:event_tablaServiciosRealizadosMouseClicked

    private void ComboCodigoDeActividadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboCodigoDeActividadItemStateChanged
     
 
      /**  String query = ComboCodigoDeActividad.getSelectedItem().toString();
        
        TableRowSorter<DefaultTableModel>tr=new TableRowSorter<DefaultTableModel>(modelo);
        tablaServiciosRealizados.setRowSorter(tr);
        
        if(query != " "){
            tr.setRowFilter(RowFilter.regexFilter(query));
        }else{
            tablaServiciosRealizados.setRowSorter(tr);
        }
     
      */  
        
    }//GEN-LAST:event_ComboCodigoDeActividadItemStateChanged

    private void btnEliminarServicioRealizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarServicioRealizadoActionPerformed
      
      
        Servicio modelS = new Servicio(); 
        ServicioDAO daoS = new ServicioDAO(); 
        
//        modelS.setiDServi(Integer.parseInt(txtEliminarActividad.getText()));
        
        if(daoS.EliminarServicio(modelS))
        {
            JOptionPane.showMessageDialog(null, "Se elimino el Servicio realizado");
            listarServicio();
             txtTotalServiciosOrden.setText(Integer.toString(suma()));  
        }
        
       
    }//GEN-LAST:event_btnEliminarServicioRealizadoActionPerformed

    private void ComboCodigoDeActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCodigoDeActividadActionPerformed
        
    
      
       
        
        
    }//GEN-LAST:event_ComboCodigoDeActividadActionPerformed

    private void txtFiltroIDReservaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroIDReservaKeyTyped
        
    
        
    }//GEN-LAST:event_txtFiltroIDReservaKeyTyped

    private void txtFiltroIDReservaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroIDReservaKeyReleased
        
        filtro(txtFiltroIDReserva.getText().toUpperCase(),tablaServiciosRealizados);
        
    }//GEN-LAST:event_txtFiltroIDReservaKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
   //     ServiciosServiexpressUI a = new ServiciosServiexpressUI(); 
   //     a.setVisible(true);
    //    this.setVisible(false);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdenServicioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdenServicioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdenServicioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdenServicioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdenServicioUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboCodigoDeActividad;
    private javax.swing.JButton btnEliminarServicioRealizado;
    private javax.swing.JButton btnEnviaradetalleFactura;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaServiciosRealizados;
    private javax.swing.JTextField txtEliminarActividad;
    private javax.swing.JTextField txtFiltroIDReserva;
    private javax.swing.JTextField txtTotalServiciosOrden;
    // End of variables declaration//GEN-END:variables
}
