/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CONTROLADOR.DetallePedidoDAO;
import MODELO.DetallePedido;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Dictionary;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pablo
 */
public class VerificarPedidoUI extends javax.swing.JFrame {
    
     DetallePedidoDAO cargarcombodetalle = new DetallePedidoDAO();
     
   

    /**
     * Creates new form VerificarPedidoUI
     */
    public VerificarPedidoUI() {
        initComponents();
        setLocationRelativeTo(null);
        ListarPedidoLista();
        cerrar();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/logoServi2.png")).getImage());
        
      //  cargarcombodetalle.consultar_producto(comboIDproducto);
     //   cargarcombodetalle.consultar_IDPEDIDO(comboIDpedido);
     //   cargarcombodetalle.consultar_proveedor(ComboProveedorDetalle);
     
    // cargarcombodetalle.consultar_estado(ComboEstadoPedido);
     
     txtCantidad.setEditable(false);
     txtcomentario.setEditable(false);
     txtPrecio.setEditable(false);
     txttotalcompra.setEditable(false);
     txtIDDELPEDIDO.setEditable(false);
     txtIDPRODUCTO.setEditable(false);
     txtPROVEEDOR.setEditable(false);
     
    }
    
    public void ListarPedidoLista()
    {
        DetallePedidoDAO ss = new DetallePedidoDAO(); 
        TabladeOrdenPedido.setModel(ss.listarDetallePedido());
        
        
    }
         public void cerrar()
    {
        try {
            
                this.setDefaultCloseOperation(AgregarClienteVehiculoUI.DO_NOTHING_ON_CLOSE);
                addWindowListener(new WindowAdapter() {
                    public void windowClosing(WindowEvent e){
                        confirmarSalida();
                    }
                });
                this.setVisible(true);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
      
     public void confirmarSalida()
    {
        int valor= JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea cerrar la apliación Serviexpress?","Advertencia", JOptionPane.YES_NO_OPTION);
        if(valor==JOptionPane.YES_OPTION)
        {
            JOptionPane.showMessageDialog(null,"Gracias, hasta pronto","Gracias",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabladeOrdenPedido = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        txtCantidad = new javax.swing.JTextField();
        txttotalcompra = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcomentario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnactualizarorden = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIDDELPEDIDO = new javax.swing.JTextField();
        txtIDPRODUCTO = new javax.swing.JTextField();
        txtPROVEEDOR = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        FechaPro = new com.toedter.calendar.JDateChooser();
        radioUNO = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Verificación Orden de Pedido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        TabladeOrdenPedido.setBackground(new java.awt.Color(102, 255, 102));
        TabladeOrdenPedido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        TabladeOrdenPedido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TabladeOrdenPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabladeOrdenPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabladeOrdenPedidoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabladeOrdenPedido);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 830, 180));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 66, 800, -1));

        txtCantidad.setBackground(new java.awt.Color(102, 255, 204));
        txtCantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 110, 20));

        txttotalcompra.setBackground(new java.awt.Color(102, 255, 204));
        txttotalcompra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txttotalcompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        jPanel1.add(txttotalcompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 140, -1));

        txtPrecio.setBackground(new java.awt.Color(102, 255, 204));
        txtPrecio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 110, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Cantidad: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Estado del pedido: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Comentario del pedido: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        txtcomentario.setBackground(new java.awt.Color(102, 255, 204));
        txtcomentario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcomentario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        jPanel1.add(txtcomentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 220, 120));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Registrar Fecha de Aprobación del pedido ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Compra Total: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 110, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Codigo del pedido:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        btnactualizarorden.setBackground(new java.awt.Color(102, 102, 255));
        btnactualizarorden.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnactualizarorden.setText("Confirmar Orden y registrar");
        btnactualizarorden.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        btnactualizarorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarordenActionPerformed(evt);
            }
        });
        jPanel1.add(btnactualizarorden, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 270, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Codigo Producto: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));

        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_exit_40px_1.png"))); // NOI18N
        jLabel10.setText("Salir");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, -1, -1));

        txtIDDELPEDIDO.setBackground(new java.awt.Color(102, 255, 204));
        txtIDDELPEDIDO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIDDELPEDIDO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        jPanel1.add(txtIDDELPEDIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 140, -1));

        txtIDPRODUCTO.setBackground(new java.awt.Color(102, 255, 204));
        txtIDPRODUCTO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIDPRODUCTO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        txtIDPRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDPRODUCTOActionPerformed(evt);
            }
        });
        jPanel1.add(txtIDPRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 140, -1));

        txtPROVEEDOR.setBackground(new java.awt.Color(102, 255, 204));
        txtPROVEEDOR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPROVEEDOR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        jPanel1.add(txtPROVEEDOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 110, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Proveedor:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Precio Unitario: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));
        jPanel1.add(FechaPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 240, 30));

        radioUNO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioUNO.setForeground(new java.awt.Color(255, 255, 255));
        radioUNO.setText("1");
        jPanel1.add(radioUNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, -1, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Aprobar orden de pedido:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnactualizarordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarordenActionPerformed
        
        SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy", Locale.getDefault());
        String date = formato.format(FechaPro.getDate());
        
        
        DetallePedido modelDP = new DetallePedido(); 
        DetallePedidoDAO daoDE = new DetallePedidoDAO();  
        
        modelDP.setCantidad(Integer.parseInt(txtCantidad.getText()));
        
         //radio buton del estado//
         
         
         if(radioUNO.isSelected())
         {
             modelDP.setEstado(Integer.parseInt(radioUNO.getText()));
         }
         
        
      //  modelDP.setEstado(Integer.parseInt(txtEstado.getText()));
        modelDP.setComentario(txtcomentario.getText());
        modelDP.setPrecioUni(Integer.parseInt(txtPrecio.getText()));
        modelDP.setTotal(Integer.parseInt(txttotalcompra.getText()));
     //   modelDP.setIdpedido(Integer.parseInt(comboIDpedido.getItemAt(comboIDpedido.getSelectedIndex())));
        modelDP.setIdpedido(Integer.parseInt(txtIDDELPEDIDO.getText()));
//        modelDP.setIdproducto(Integer.parseInt(comboIDproducto.getItemAt(comboIDproducto.getSelectedIndex())));
        modelDP.setIdproducto(Integer.parseInt(txtIDPRODUCTO.getText()));
        modelDP.setFechaVencimiento(date);
    //    modelDP.setFechaVencimiento(txtFechaVencimientoDetalle.getText());
       // modelDP.setRutProveedor(ComboProveedorDetalle.getItemAt(ComboProveedorDetalle.getSelectedIndex()));
       modelDP.setRutProveedor(txtPROVEEDOR.getText());
        if(daoDE.ModificarDetallePedido(modelDP))
        {
            JOptionPane.showMessageDialog(null, "Se Actualizo el estado del pedido");
            ListarPedidoLista();
        }
        
        
        
    }//GEN-LAST:event_btnactualizarordenActionPerformed

    private void TabladeOrdenPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabladeOrdenPedidoMouseClicked
      

       
        SimpleDateFormat formatter = new SimpleDateFormat("dd-M-yyyy");
        java.util.Date date = new java.util.Date();
        String formattedDate = formatter.format(date);
        try {
            java.util.Date parsedDate = formatter.parse(formattedDate);
        } catch (ParseException ex) {
            Logger.getLogger(ProductosUI.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        int seleccion = TabladeOrdenPedido.rowAtPoint(evt.getPoint()); 
        
        txtCantidad.setText(TabladeOrdenPedido.getValueAt(seleccion, 0)+"");
        //radioCero.setText(TabladeOrdenPedido.getValueAt(seleccion, 1)+"");
        txtcomentario.setText(TabladeOrdenPedido.getValueAt(seleccion, 2)+"");
        txtPrecio.setText(TabladeOrdenPedido.getValueAt(seleccion, 3)+"");
        txttotalcompra.setText(TabladeOrdenPedido.getValueAt(seleccion, 4)+"");
        txtIDDELPEDIDO.setText(TabladeOrdenPedido.getValueAt(seleccion, 5)+"");
        txtIDPRODUCTO.setText(TabladeOrdenPedido.getValueAt(seleccion, 6)+"");
        txtPROVEEDOR.setText(TabladeOrdenPedido.getValueAt(seleccion, 7)+"");
       // FechaPro.setDate(date);
      
        
        
        
    }//GEN-LAST:event_TabladeOrdenPedidoMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        MenuUI mm = new MenuUI();
        mm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void txtIDPRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDPRODUCTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDPRODUCTOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerificarPedidoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerificarPedidoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerificarPedidoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerificarPedidoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerificarPedidoUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FechaPro;
    private javax.swing.JTable TabladeOrdenPedido;
    private javax.swing.JButton btnactualizarorden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton radioUNO;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIDDELPEDIDO;
    private javax.swing.JTextField txtIDPRODUCTO;
    private javax.swing.JTextField txtPROVEEDOR;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtcomentario;
    private javax.swing.JTextField txttotalcompra;
    // End of variables declaration//GEN-END:variables
}
